# -*- makefile -*- Time-stamp: <08/06/29 19:23:01 ptr>

#PRGNAME = misc_sut
PRGNAMES = opts_ut
#SRC_CC = unit_test.cc \
#         opts_test.cc opts_test_suite.cc
opts_ut_SRC_CC = opts_ut.cc \
         opts_test.cc opts_test_suite.cc
