#define _STLP_PLATFORM "Embedded AVR-libc"

#define _STLP_AVR 1

#define _STLP_LITTLE_ENDIAN 1
#define _STLP_NO_THREADS
#define _STLP_DONT_USE_EXCEPTIONS 1
#define _STLP_USE_STDIO_IO
#define _STLP_NO_WCHAR_T  1
#define _STLP_NO_RTTI 1
#define _STLP_NO_TYPEINFO 1
//#define   _STLP_NO_AT_MEMBER_FUNCTION 1
#define _STLP_NO_EXCEPTION_HEADER 1
#define _STLP_NO_NATIVE_WIDE_STREAMS 1
#define _STLP_NO_NATIVE_MBSTATE_T 1
#define _STLP_NO_LONG_DOUBLE 1
#define _STLP_NO_VENDOR_MATH_L 1

#undef max
#undef min

